process.env.MATCH_MAKER_URL = 'test'
process.env.MATCH_MAKER_SECRET_TOKEN = 'test'
process.env.SERVER_ID = 'server1'
process.env.SECRET_TOKEN = 'test'
process.env.KUBECONFIG = '{ "apiVersion": "1", "clusters": [ { "cluster": {} } ], "users": [ { "user": {} } ] }'