[compilerOptions.build]
  pwaEnabled = false
  outputDir = "./browser"

[vite.build.lib]
    entry = "runtime.ts"
    name = "RPG"
    fileName = "rpg.runtime"

[vite.build.rollupOptions.output]
  format = "umd"

[vite.build.rollupOptions]
  external = ["vue", "react", "react-dom"]