version: 0.0

os: linux

files:
  - source: /
    destination: /var/games/tinygames

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/npm-install.sh
      runas: ec2-user
      timeout: 300
  ApplicationStart:
    - location: scripts/npm-start.sh
      runas: ec2-user
      timeout: 60
