export enum Effect {
    NONE = 'NONE',
    CAN_NOT_SKILL = 'CAN_NOT_SKILL',
    CAN_NOT_ITEM = 'CAN_NOT_ITEM',
    ALWAYS_ATTACK_ENEMIES = 'ALWAYS_ATTACK_ENEMIES',
    CAN_NOT_EVADE = 'CAN_NOT_EVADE',
    CAN_NOT_GET_EXP = 'CAN_NOT_GET_EXP',
    CAN_NOT_GET_GOLD = 'CAN_NOT_GET_GOLD',
    PHARMACOLOGY = 'PHARMACOLOGY',
    CRITICAL_BONUS = 'CRITICAL_BONUS',
    SUPER_GUARD = 'SUPER_GUARD',
    GUARD = 'GUARD'
}
